"""
app/api/v1/generate.py

AI document generation endpoint.
Accepts a plain-text prompt and a desired output format, calls Qwen-Max to
generate structured content, and returns a ready-to-download file.

Supported formats:
  md   — Markdown  (.md)  — returned as UTF-8 text.
  pdf  — PDF       (.pdf) — Markdown converted to PDF via fpdf2 (pure Python,
                             no system-level dependencies).
  csv  — CSV       (.csv) — Qwen is prompted to return raw CSV, no wrappers.

Page sizes (PDF only):
  A4 (default) — 210 × 297 mm
  A3           — 297 × 420 mm

The endpoint is auth-protected — the generated content is attributed to the
requesting user. No memory is updated; this is a one-shot generation.

Used by: app/api/v1/router.py, src/api/generate.js.
"""

import logging
import re
from datetime import UTC, datetime

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import Response
from pydantic import BaseModel, Field

from app.dependencies import get_current_user
from app.schemas.auth import UserOut
from app.services.memory_engine.qwen_router import generate

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/generate", tags=["generate"])

# ---------------------------------------------------------------------------
# Request schema
# ---------------------------------------------------------------------------


class GenerateRequest(BaseModel):
    """
    Body for POST /generate.

    Parameters:
        prompt  (str)  — plain-text description of what to generate.
        format  (str)  — "md" | "pdf" | "csv"
        size    (str)  — "A4" | "A3". Ignored for md/csv. Default "A4".
    """

    prompt: str = Field(..., min_length=5, max_length=2000)
    format: str = Field(..., pattern="^(md|pdf|csv)$")
    size:   str = Field(default="A4", pattern="^(A4|A3)$")


# ---------------------------------------------------------------------------
# System prompts
# ---------------------------------------------------------------------------

_DOC_SYSTEM = """You are a professional document writer for Hipocampus, an AI memory system.
Generate a comprehensive, well-structured document based on the user's request.

Use proper Markdown formatting:
  # Title              — document title (one only)
  ## Section           — major section headings
  ### Subsection       — subsection headings
  - bullet             — unordered list items
  1. item              — ordered list items
  **bold**             — emphasis on key terms
  `inline code`        — technical terms
  ```lang\n...\n```   — code blocks with language hint
  | col | col |       — tables when data is tabular

Be thorough, professional, and well-organised. Length should match the scope of the request."""

_CSV_SYSTEM = """You are a data analyst generating CSV files.
Return ONLY the raw CSV content — nothing else.
No markdown, no code fences, no explanation text.
Start directly with the header row, then data rows.
Use comma as delimiter. Quote strings that contain commas."""


# ---------------------------------------------------------------------------
# PDF renderer (Markdown → fpdf2)
# ---------------------------------------------------------------------------


def _markdown_to_pdf(content: str, page_size: str) -> bytes:
    """
    Converts a Markdown string to a PDF using fpdf2 (pure Python).

    Handles:
      H1 / H2 / H3 headings, bullet and numbered lists, code blocks,
      bold (**), italic (*), inline code, paragraph spacing.

    Parameters:
        content   (str) — Markdown text from Qwen.
        page_size (str) — "A4" or "A3".

    Returns:
        bytes — raw PDF binary.
    """
    from fpdf import FPDF

    # ── PDF setup ──────────────────────────────────────────────────────────
    pdf = FPDF(orientation="P", unit="mm", format=page_size)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Margins: 20 mm on each side
    margin = 20
    pdf.set_left_margin(margin)
    pdf.set_right_margin(margin)

    # ── Header ─────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    gen_time = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, f"Generated by Hipocampus · {gen_time}", align="R")
    pdf.ln(8)

    # ── Helpers ────────────────────────────────────────────────────────────
    def strip_inline(text: str) -> str:
        """Remove **/*/` markers, leaving only the inner text."""
        text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
        text = re.sub(r"\*(.+?)\*",     r"\1", text)
        text = re.sub(r"`(.+?)`",        r"\1", text)
        return text

    def write_para(text: str, size: int = 11, style: str = "") -> None:
        pdf.set_font("Helvetica", style, size)
        pdf.set_text_color(0, 0, 0)
        clean = strip_inline(text).strip()
        if clean:
            pdf.multi_cell(0, 6, clean)

    # ── Render lines ───────────────────────────────────────────────────────
    lines       = content.split("\n")
    in_code     = False
    code_buffer: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        raw  = line.rstrip()

        # Code fence start / end
        if raw.startswith("```"):
            if in_code:
                # Flush code block
                in_code = False
                if code_buffer:
                    pdf.set_fill_color(245, 245, 245)
                    pdf.set_draw_color(220, 220, 220)
                    pdf.set_font("Courier", "", 9)
                    pdf.set_text_color(30, 30, 30)
                    block = "\n".join(code_buffer)
                    pdf.multi_cell(0, 5, block, border=1, fill=True)
                    pdf.ln(3)
                code_buffer = []
            else:
                in_code = True
            i += 1
            continue

        if in_code:
            code_buffer.append(raw)
            i += 1
            continue

        # Headings
        if raw.startswith("# "):
            pdf.set_font("Helvetica", "B", 22)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)
            pdf.multi_cell(0, 10, strip_inline(raw[2:]))
            pdf.ln(2)

        elif raw.startswith("## "):
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(6)
            pdf.multi_cell(0, 8, strip_inline(raw[3:]))
            # Underline rule
            pdf.set_draw_color(200, 200, 200)
            x = pdf.get_x()
            y = pdf.get_y()
            pdf.line(margin, y, pdf.w - margin, y)
            pdf.ln(3)

        elif raw.startswith("### "):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(40, 40, 40)
            pdf.ln(4)
            pdf.multi_cell(0, 7, strip_inline(raw[4:]))
            pdf.ln(1)

        # Bullet lists
        elif raw.startswith("- ") or raw.startswith("* "):
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(0, 0, 0)
            pdf.set_x(margin + 5)
            pdf.multi_cell(
                pdf.w - 2 * margin - 5,
                6,
                f"\u2022  {strip_inline(raw[2:])}",
            )

        # Numbered lists
        elif re.match(r"^\d+\. ", raw):
            txt = re.sub(r"^\d+\. ", "", raw)
            m   = re.match(r"^(\d+)\. ", raw)
            num = m.group(1) if m else "•"
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(0, 0, 0)
            pdf.set_x(margin + 5)
            pdf.multi_cell(
                pdf.w - 2 * margin - 5, 6,
                f"{num}.  {strip_inline(txt)}",
            )

        # Horizontal rule
        elif raw.startswith("---") or raw.startswith("***"):
            pdf.ln(4)
            pdf.set_draw_color(200, 200, 200)
            y = pdf.get_y()
            pdf.line(margin, y, pdf.w - margin, y)
            pdf.ln(4)

        # Empty line → paragraph spacing
        elif not raw:
            pdf.ln(4)

        # Normal paragraph
        else:
            write_para(raw)

        i += 1

    # ── Footer ─────────────────────────────────────────────────────────────
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(0, 10, f"Page {pdf.page_no()}", align="C")

    return bytes(pdf.output())


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post(
    "",
    status_code=200,
    summary="Generate a document (MD / PDF / CSV)",
)
async def generate_document(
    body: GenerateRequest,
    current_user: UserOut = Depends(get_current_user),
) -> Response:
    """
    Generates a document using Qwen-Max and returns it as a downloadable file.

    The format determines the system prompt strategy:
      md/pdf — Qwen writes structured Markdown; pdf additionally converts
               the Markdown to a clean PDF using fpdf2.
      csv    — Qwen is constrained to return raw CSV with no wrappers.

    Parameters:
        body         (GenerateRequest) — {prompt, format, size}
        current_user (UserOut)         — authenticated user (auth-gated).

    Returns:
        Response — binary or text file with appropriate Content-Type and
                   Content-Disposition headers for in-browser download.

    Raises:
        HTTPException 500 — Qwen API or PDF rendering failure.
    """
    fmt    = body.format
    size   = body.size
    prompt = body.prompt.strip()

    logger.info(
        "Document generation: format=%s size=%s user=%s",
        fmt, size, current_user.id,
    )

    # ── Call Qwen ────────────────────────────────────────────────────────
    try:
        if fmt == "csv":
            md_content = await generate(
                system_prompt=_CSV_SYSTEM,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=4096,
            )
        else:
            # Both md and pdf get the same structured-document prompt
            md_content = await generate(
                system_prompt=_DOC_SYSTEM,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.4,
                max_tokens=4096,
            )
    except Exception as exc:
        logger.error("Qwen generation error for user %s: %s", current_user.id, exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Document generation failed — Qwen API error. Please try again.",
        )

    # ── Render and return ────────────────────────────────────────────────
    timestamp = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")

    if fmt == "md":
        return Response(
            content=md_content.encode("utf-8"),
            media_type="text/markdown; charset=utf-8",
            headers={
                "Content-Disposition":
                    f'attachment; filename="hipocampus-{timestamp}.md"',
            },
        )

    if fmt == "csv":
        # Strip any accidental markdown wrapping Qwen might add
        csv_content = re.sub(r"^```(?:csv)?\n?", "", md_content).rstrip("`").strip()
        return Response(
            content=csv_content.encode("utf-8"),
            media_type="text/csv; charset=utf-8",
            headers={
                "Content-Disposition":
                    f'attachment; filename="hipocampus-{timestamp}.csv"',
            },
        )

    if fmt == "pdf":
        try:
            pdf_bytes = _markdown_to_pdf(md_content, size)
        except Exception as exc:
            logger.error("PDF rendering error for user %s: %s", current_user.id, exc)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="PDF rendering failed. Try the MD format instead.",
            )
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition":
                    f'attachment; filename="hipocampus-{timestamp}.pdf"',
            },
        )

    # Unreachable — pydantic validates format above
    raise HTTPException(status_code=400, detail="Unsupported format.")