"""
app/models/chat.py

Two ORM models that add persistent chat history on top of the existing
memory architecture without touching any core table.

Chat
    Metadata for a single conversation thread. One row per conversation.
    The `session_id` column is the join key shared by:
      - the Redis working-memory buffer  (session:{user_id}:{session_id}:buffer)
      - the episodes table               (episodes.session_id)
      - the messages table               (messages.session_id)
    Nothing else in the core changes — session_id was already threaded
    through every layer. Chat is purely additive metadata.

Message
    Permanent archive of every raw user ↔ assistant turn.
    Redis still drives the AI's context window (working memory, 1-hour TTL).
    Message gives users access to their full conversation history forever —
    copying code from two days ago, reviewing what was decided, etc.
    These are two different responsibilities that coexist without conflict.

Relationship:
    users  1──* chats  1──* messages

Used by:
    app/api/v1/chats.py         — all new chat/history endpoints
    app/services/chat_service.py — saves each turn after process_turn()
    app/models/__init__.py      — imported for Alembic autogenerate
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db import Base
from app.models.base import TimestampMixin, UUIDMixin


class Chat(UUIDMixin, TimestampMixin, Base):
    """
    Represents a single named conversation thread.

    Columns:
        id         — UUID primary key (from UUIDMixin).
        user_id    — FK to users.id; every chat belongs to exactly one user.
        session_id — Short opaque string that ties this chat to:
                       • the Redis buffer key
                       • Episode rows (episodes.session_id)
                       • Message rows (messages.session_id)
                     Unique per chat — two chats can never share a session.
        title      — Nullable until Qwen generates it after the first turn.
                     4–6 word summary of the first user message.
                     Can also be renamed manually via PATCH /api/v1/chats/{id}.
        created_at — Set on INSERT (from TimestampMixin).
        updated_at — Refreshed when the title is updated (from TimestampMixin).

    Relationships:
        messages   — ordered list of Message rows for this chat (backref).

    Used by:
        app/api/v1/chats.py          — created on POST /chats, listed on GET /chats
        app/services/chat_service.py — looked up by session_id on each turn
    """

    __tablename__ = "chats"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Owner of this conversation thread.",
    )

    session_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        unique=True,
        index=True,
        comment=(
            "Join key shared with episodes.session_id and the Redis buffer. "
            "Generated server-side as a short UUID on chat creation."
        ),
    )

    title: Mapped[str | None] = mapped_column(
        String(256),
        nullable=True,
        default=None,
        comment=(
            "4–6 word summary generated by Qwen after the first turn. "
            "NULL until generation completes. Can be overridden by the user."
        ),
    )

    # Relationship: one Chat has many Messages ordered by created_at.
    # lazy='dynamic' is avoided — use explicit queries instead.
    messages: Mapped[list["Message"]] = relationship(
        "Message",
        back_populates="chat",
        order_by="Message.created_at",
        cascade="all, delete-orphan",
    )


class Message(UUIDMixin, Base):
    """
    Permanent archive of a single user or assistant turn.

    Why this exists alongside the Redis buffer:
        Redis holds the last 10 messages (working memory, 1-hour TTL).
        Message holds every turn forever so users can retrieve code,
        decisions, and context from any previous session without asking
        the AI again. Two different responsibilities — both are needed.

    Columns:
        id         — UUID primary key (from UUIDMixin).
        chat_id    — FK to chats.id; every message belongs to one chat.
        session_id — Redundant copy of chats.session_id for fast direct
                     queries without a join (e.g. "all messages for this
                     session_id" used by GET /chats/{id}/messages).
        role       — "user" or "assistant". Validated at the service layer.
        content    — The raw message text. No size limit — the user may
                     paste long code blocks or receive long responses.
        created_at — Set on INSERT. Messages are immutable: no updated_at.

    Relationship:
        chat       — the parent Chat (backref from Chat.messages).

    Used by:
        app/services/chat_service.py — one INSERT per turn in process_turn()
        app/api/v1/chats.py          — GET /chats/{id}/messages
    """

    __tablename__ = "messages"

    chat_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chats.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Parent conversation thread.",
    )

    session_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment=(
            "Redundant copy of chats.session_id enabling direct "
            "session-keyed queries without joining chats."
        ),
    )

    role: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        comment="'user' or 'assistant' — validated at service layer.",
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Raw message text. Immutable after insert.",
    )

    # Messages are immutable — only created_at, no updated_at.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationship back to parent Chat.
    chat: Mapped["Chat"] = relationship("Chat", back_populates="messages")